### ISSUE TITLE
add fucking recurring reminders you meme

### ISSUE THREAD

**Issue by Aetheryx** [Aetheryx/remindme#21]
sorry dad

**Comment by Aetheryx** [comment]
mostly fixed in https://github.com/Aetheryx/remindme/commit/70a078c1f2316d51cd4b6d3d72308c1247e5950d

**Comment by kurtextrem** [comment]
How can I use this?

**Comment by Aetheryx** [comment]
Recurring reminders were briefly on the main bot, you could make them with the `-r` flag at the end of a message. The feature has now been removed due to a lethal bug on the main bot, due to lack of backwards compatibility with the old schema which resulted in [old reminders being flagged as recurring and instantly re-sent](https://cl.ly/3C330D0U3n3E) in a deadly loop.  
For now, if you want recurring reminders you'll have to wait for me to refactor them with compatibility or you can host your own instance.

**Comment by Aetheryx** [comment]
feature added (indev); see https://github.com/Aetheryx/remindme/commit/edd7a7272a62e8ca24f4d6319369a3df437c381f
