### ISSUE TITLE
Feature Request: make the bot reply to PM messages (outside of channels)

### ISSUE THREAD

**Issue by danielesegato** [Aetheryx/remindme#5]
Useful to set personal reminders without bothering others on the server.

**Comment by Aetheryx** [comment]
Been considering this for a while. Shouldn't be too hard to do, why not? Will get back to you when it's done.

**Comment by danielesegato** [comment]
Thanks!

**Comment by Aetheryx** [comment]
Added DM support. Should be the same usage as what you have in a normal guild, aside from the lack of custom prefixes (it's always `r>` in DMs), and no `purge` or `prefix` commands.

**Comment by danielesegato** [comment]
@Aetheryx awesome! is this already available in any running instance?

**Comment by Aetheryx** [comment]
Yep! It's live as we speak.
