### ISSUE TITLE
Reminders in channel

### ISSUE THREAD

**Issue by Greg-Boggs** [Aetheryx/remindme#6]
Is there an option to send the reminders to the channel rather than in private message?

**Comment by Aetheryx** [comment]
Nope. I've been saying I'll "do this soon" for so long now and it's still definitely something I want to do, but I'm drowning in school work and other projects -- so to be honest, don't expect it any time soon. But it's certain gone yet.

**Comment by Aetheryx** [comment]
I don't see myself charging for any features any time soon - RemindMeBot is very light, and as of right now I have no VPS fees to consider (Digital Ocean student plan <3). I plan to keep RemindMeBot 100% free forever, and I know that's an ambition lots of bot creators have.. but I honestly can't see myself charging for features.  
I've been stalking your profile a bit. Thanks for the compliment, means **alot** coming from someone like you!!

**Comment by Greg-Boggs** [comment]
👍

**Comment by Aetheryx** [comment]
Added as of 1.5.0. Append a `channel: #channel` to your message for the shorthand method, or just follow the instructions on the guided tour method.
